const router = require("express").Router();
const user = require("./user");
const site = require("./site");
const request = require("./request");
const file = require("./file");
const materialTotal = require("./materialTotal");
const pushNotification = require("./pushNotificationService");
const chat = require("./chat");
const stageMaterial = require("./stageMaterial");
const stage = require("./stage");
const product = require("./product");
const extraMaterials = require("./extraMatrial");
const contractorData = require("./contractorData");
const agreementData = require("./agreementData");
const dailyUpdate = require("./dailyUpdate");
const task = require("./task");

router.use("/user", user);
router.use("/site", site);
router.use("/request", request);
router.use("/file", file);
router.use("/materialTotal", materialTotal);
router.use("/notification", pushNotification);
router.use("/chat", chat);
router.use("/stageMaterial", stageMaterial);
router.use("/stage", stage);
router.use("/product", product);
router.use("/extraMaterial", extraMaterials);
router.use("/contractorData", contractorData);
router.use("/agreementData", agreementData);
router.use("/dailyUpdate", dailyUpdate);
router.use("/task", task);
module.exports = router;
